# Generated by Django 5.2.15 on 2026-08-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0034_seed_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfinancesettings',
            name='exchange_rate_source',
            field=models.CharField(choices=[('GLOBAL', 'Global Exchange Rate'), ('CUSTOM', 'Company Custom Rate')], default='GLOBAL', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_exchange_rates', to='tenants.company')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_from_rates', to='tenants.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_to_rates', to='tenants.currency')),
            ],
            options={
                'unique_together': {('company', 'from_currency', 'to_currency')},
            },
        ),
    ]
