# Generated by Django 5.2.15 on 2026-08-10 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0035_companyfinancesettings_exchange_rate_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('HR', 'HR'), ('PAYROLL', 'Payroll'), ('ACCOUNTING', 'Accounting'), ('IT', 'IT')], max_length=30)),
                ('provider', models.CharField(choices=[('BAMBOOHR', 'BambooHR'), ('RIPPLING', 'Rippling'), ('ADP', 'ADP'), ('WORKDAY', 'Workday'), ('GUSTO', 'Gusto'), ('DEEL', 'Deel'), ('QUICKBOOKS', 'QuickBooks'), ('XERO', 'Xero'), ('SAGE', 'Sage'), ('NETSUITE', 'NetSuite'), ('FRESHBOOKS', 'FreshBooks'), ('ZOHO_BOOKS', 'Zoho Books'), ('OKTA', 'Okta'), ('MICROSOFT_ENTRA', 'Microsoft Entra ID'), ('JUMP_CLOUD', 'JumpCloud'), ('ONE_LOGIN', 'OneLogin'), ('GOOGLE_WORKSPACE', 'Google Workspace')], max_length=50)),
                ('status', models.CharField(choices=[('DISCONNECTED', 'Disconnected'), ('CONNECTED', 'Connected'), ('ERROR', 'Error')], default='DISCONNECTED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_integrations', to='tenants.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'provider'), name='unique_company_integration_provider')],
            },
        ),
    ]
