# Generated by Django 5.2.15 on 2026-08-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0036_companyintegration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyIntegration',
        ),
    ]
