# Generated by Django 5.2.15 on 2026-08-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0037_delete_companyintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='old_bill_limit_days',
            field=models.PositiveIntegerField(default=90, help_text='Maximum number of days old a receipt can be for reimbursement.'),
        ),
    ]
