# Generated by Django 5.2.15 on 2026-08-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0037_delete_companyintegration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.company",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("COMPANY_ADMIN", "Company Admin"),
                    ("MANAGER", "Manager"),
                    ("ACCOUNTS", "Accounts"),
                    ("EMPLOYEE", "Employee"),
                    ("PLATFORM_ADMIN", "Platform Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
