# Generated by Django 5.2.15 on 2026-08-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0038_companypolicy_old_bill_limit_days'),
        ('tenants', '0038_userprofile_platform_admin_nullable_company'),
    ]

    operations = [
    ]
