# Generated by Django 5.2.15 on 2026-08-13 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0039_merge_20260813_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmailIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reimbursement_email', models.EmailField(max_length=254)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_username', models.EmailField(max_length=254)),
                ('imap_password', models.CharField(max_length=500)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_integration', to='tenants.company')),
            ],
        ),
    ]
