# Generated by Django 5.2.15 on 2026-08-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0040_companyemailintegration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='inbound_email_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='inbound_forwarding_email',
        ),
        migrations.AddField(
            model_name='company',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='imap_password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='imap_port',
            field=models.PositiveIntegerField(default=993),
        ),
        migrations.AddField(
            model_name='company',
            name='imap_username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
