# Generated by Django 5.2.15 on 2026-08-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0041_remove_company_inbound_email_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrole',
            name='can_manage_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='can_manage_departments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='can_manage_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='can_manage_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='can_manage_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='can_manage_workflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='can_view_company_reports',
            field=models.BooleanField(default=False),
        ),
    ]
