# Generated by Django 5.2.15 on 2026-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0042_companyrole_can_manage_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrole',
            name='can_manage_integrations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='can_view_integrations',
            field=models.BooleanField(default=False),
        ),
    ]
