# Generated by Django 5.2.15 on 2026-09-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0044_ensure_companyrole_permission_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
