import logging
from urllib.parse import urlencode

import requests
from django.conf import settings


logger = logging.getLogger(__name__)


# ==========================================================
# EXCEPTIONS
# ==========================================================


class QuickBooksIntegrationError(Exception):
    """
    Base QuickBooks integration exception.
    """


class QuickBooksAuthenticationError(
    QuickBooksIntegrationError
):
    """
    QuickBooks authentication/authorization failed.
    """


class QuickBooksConnectionError(
    QuickBooksIntegrationError
):
    """
    Unable to communicate with QuickBooks.
    """


class QuickBooksPermissionError(
    QuickBooksIntegrationError
):
    """
    QuickBooks rejected the requested operation
    because of insufficient permissions.
    """


# ==========================================================
# QUICKBOOKS OAUTH CLIENT
# ==========================================================


class QuickBooksClient:
    """
    QuickBooks Online OAuth 2.0 client used by ZepEx.

    Responsible for:

    - generating authorization URLs
    - exchanging authorization codes
    - refreshing access tokens
    - making QuickBooks API requests
    """

    AUTHORIZE_URL = (
        "https://appcenter.intuit.com/connect/oauth2"
    )

    TOKEN_URL = (
        "https://oauth.platform.intuit.com/"
        "oauth2/v1/tokens/bearer"
    )

    ACCOUNTING_SCOPE = (
        "com.intuit.quickbooks.accounting"
    )

    SANDBOX_API_BASE = (
        "https://sandbox-quickbooks.api.intuit.com"
    )

    PRODUCTION_API_BASE = (
        "https://quickbooks.api.intuit.com"
    )

    def __init__(
        self,
        *,
        client_id=None,
        client_secret=None,
        redirect_uri=None,
        environment=None,
        timeout=30,
    ):

        self.client_id = (
            client_id
            or settings.QUICKBOOKS_CLIENT_ID
        )

        self.client_secret = (
            client_secret
            or settings.QUICKBOOKS_CLIENT_SECRET
        )

        self.redirect_uri = (
            redirect_uri
            or settings.QUICKBOOKS_REDIRECT_URI
        )

        self.environment = (
            environment
            or settings.QUICKBOOKS_ENVIRONMENT
            or "sandbox"
        ).lower()

        self.timeout = timeout

        # --------------------------------------------------
        # Validate configuration
        # --------------------------------------------------

        if not self.client_id:
            raise ValueError(
                "QUICKBOOKS_CLIENT_ID is not configured."
            )

        if not self.client_secret:
            raise ValueError(
                "QUICKBOOKS_CLIENT_SECRET is not configured."
            )

        if not self.redirect_uri:
            raise ValueError(
                "QUICKBOOKS_REDIRECT_URI is not configured."
            )

        if self.environment not in (
            "sandbox",
            "production",
        ):
            raise ValueError(
                "QUICKBOOKS_ENVIRONMENT must be "
                "'sandbox' or 'production'."
            )

    # ======================================================
    # AUTHORIZATION URL
    # ======================================================

    def get_authorization_url(
        self,
        *,
        state,
    ):
        """
        Generate the Intuit OAuth authorization URL.

        The state value must be generated by ZepEx
        and validated when Intuit calls our callback.
        """

        if not state:
            raise ValueError(
                "OAuth state is required."
            )

        params = {
            "client_id": self.client_id,
            "response_type": "code",
            "scope": self.ACCOUNTING_SCOPE,
            "redirect_uri": self.redirect_uri,
            "state": state,
        }

        return (
            f"{self.AUTHORIZE_URL}?"
            f"{urlencode(params)}"
        )

    # ======================================================
    # EXCHANGE AUTHORIZATION CODE
    # ======================================================

    def exchange_authorization_code(
        self,
        *,
        code,
    ):
        """
        Exchange the authorization code returned by
        Intuit for access and refresh tokens.
        """

        if not code:
            raise ValueError(
                "QuickBooks authorization code is required."
            )

        data = {
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": self.redirect_uri,
        }

        return self._token_request(
            data=data
        )

    # ======================================================
    # REFRESH TOKEN
    # ======================================================

    def refresh_access_token(
        self,
        *,
        refresh_token,
    ):
        """
        Generate a new QuickBooks access token.

        IMPORTANT:
        Intuit can return a new refresh token.
        Always save the latest refresh token.
        """

        if not refresh_token:
            raise ValueError(
                "QuickBooks refresh token is required."
            )

        data = {
            "grant_type": "refresh_token",
            "refresh_token": refresh_token,
        }

        return self._token_request(
            data=data
        )

    # ======================================================
    # INTERNAL TOKEN REQUEST
    # ======================================================

    def _token_request(
        self,
        *,
        data,
    ):

        try:

            response = requests.post(
                self.TOKEN_URL,
                data=data,
                auth=(
                    self.client_id,
                    self.client_secret,
                ),
                headers={
                    "Accept": "application/json",
                    "Content-Type": (
                        "application/"
                        "x-www-form-urlencoded"
                    ),
                },
                timeout=self.timeout,
            )

        except requests.Timeout as exc:

            raise QuickBooksConnectionError(
                "QuickBooks token request timed out."
            ) from exc

        except requests.ConnectionError as exc:

            raise QuickBooksConnectionError(
                "Unable to connect to QuickBooks."
            ) from exc

        except requests.RequestException as exc:

            raise QuickBooksConnectionError(
                "QuickBooks token request failed."
            ) from exc

        if response.status_code in (
            400,
            401,
        ):

            try:
                error_data = response.json()
            except ValueError:
                error_data = {}

            error_description = (
                error_data.get(
                    "error_description"
                )
                or error_data.get(
                    "error"
                )
                or (
                    "QuickBooks authorization failed."
                )
            )

            raise QuickBooksAuthenticationError(
                error_description
            )

        if response.status_code >= 500:

            raise QuickBooksConnectionError(
                "QuickBooks authorization service "
                "is temporarily unavailable."
            )

        if not response.ok:

            raise QuickBooksIntegrationError(
                "QuickBooks token request failed "
                f"with status {response.status_code}."
            )

        try:

            return response.json()

        except ValueError as exc:

            raise QuickBooksIntegrationError(
                "QuickBooks returned an invalid "
                "token response."
            ) from exc

    # ======================================================
    # API BASE URL
    # ======================================================

    @property
    def api_base_url(self):

        if self.environment == "production":
            return self.PRODUCTION_API_BASE

        return self.SANDBOX_API_BASE

    # ======================================================
    # QUICKBOOKS API REQUEST
    # ======================================================

    def request(
        self,
        method,
        endpoint,
        *,
        access_token,
        params=None,
        json=None,
    ):
        """
        Make an authenticated request to the
        QuickBooks Online Accounting API.
        """

        if not access_token:
            raise ValueError(
                "QuickBooks access token is required."
            )

        url = (
            f"{self.api_base_url}/"
            f"{endpoint.lstrip('/')}"
        )

        headers = {
            "Authorization": (
                f"Bearer {access_token}"
            ),
            "Accept": "application/json",
            "Content-Type": "application/json",
        }

        try:

            response = requests.request(
                method=method,
                url=url,
                headers=headers,
                params=params,
                json=json,
                timeout=self.timeout,
            )

        except requests.Timeout as exc:

            raise QuickBooksConnectionError(
                "QuickBooks API request timed out."
            ) from exc

        except requests.ConnectionError as exc:

            raise QuickBooksConnectionError(
                "Unable to connect to QuickBooks."
            ) from exc

        except requests.RequestException as exc:

            raise QuickBooksConnectionError(
                "QuickBooks API request failed."
            ) from exc

        # --------------------------------------------------
        # Expired / invalid token
        # --------------------------------------------------

        if response.status_code == 401:

            raise QuickBooksAuthenticationError(
                "QuickBooks access token is invalid "
                "or has expired."
            )

        # --------------------------------------------------
        # Permission
        # --------------------------------------------------

        if response.status_code == 403:

            raise QuickBooksPermissionError(
                "QuickBooks denied access to "
                "this resource."
            )

        # --------------------------------------------------
        # Rate limit
        # --------------------------------------------------

        if response.status_code == 429:

            raise QuickBooksConnectionError(
                "QuickBooks API rate limit reached."
            )

        # --------------------------------------------------
        # Server error
        # --------------------------------------------------

        if response.status_code >= 500:

            raise QuickBooksConnectionError(
                "QuickBooks is temporarily unavailable."
            )

        if not response.ok:

            try:
                error_data = response.json()
            except ValueError:
                error_data = None

            logger.error(
                "QuickBooks API error. "
                "status=%s response=%s",
                response.status_code,
                error_data,
            )

            raise QuickBooksIntegrationError(
                "QuickBooks API request failed "
                f"with status {response.status_code}."
            )

        try:

            return response.json()

        except ValueError as exc:

            raise QuickBooksIntegrationError(
                "QuickBooks returned an invalid "
                "JSON response."
            ) from exc

    # ======================================================
    # COMPANY INFORMATION
    # ======================================================

    def get_company_info(
        self,
        *,
        realm_id,
        access_token,
    ):
        """
        Fetch the connected QuickBooks company.

        Useful for:
        - testing the connection
        - showing connected company name
        - validating realmId
        """

        if not realm_id:
            raise ValueError(
                "QuickBooks realm ID is required."
            )

        return self.request(
            "GET",
            (
                f"v3/company/{realm_id}/"
                f"companyinfo/{realm_id}"
            ),
            access_token=access_token,
        )

    def get_accounts(
        self,
        *,
        realm_id,
        access_token,
    ):
        """
        Fetch QuickBooks accounts for the connected company.

        We only need accounts that can be used for
        reimbursement/accounting mapping.
        """

        if not realm_id:
            raise ValueError(
                "QuickBooks realm ID is required."
            )

        query = (
            "select * from Account "
            "where Active = true "
            "order by Name"
        )

        return self.request(
            "GET",
            (
                f"v3/company/{realm_id}/query"
            ),
            access_token=access_token,
            params={
                "query": query,
                "minorversion": "75",
            },
        )

    def create_purchase(
        self,
        *,
        realm_id,
        access_token,
        purchase_data,
    ):
        """
        Create an expense/purchase transaction
        in QuickBooks Online.
        """

        if not realm_id:
            raise ValueError(
                "QuickBooks realm ID is required."
            )

        if not purchase_data:
            raise ValueError(
                "QuickBooks purchase data is required."
            )

        return self.request(
            "POST",
            f"v3/company/{realm_id}/purchase",
            access_token=access_token,
            json=purchase_data,
        )