# Generated by Django 5.2.15 on 2026-08-10 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0035_companyfinancesettings_exchange_rate_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('HRMS', 'HR & Employee'), ('PAYROLL', 'Payroll'), ('ACCOUNTING', 'Accounting'), ('IT', 'IT & Identity'), ('ERP', 'ERP')], max_length=30)),
                ('provider', models.CharField(choices=[('BAMBOOHR', 'BambooHR'), ('RIPPLING', 'Rippling'), ('WORKDAY', 'Workday'), ('HIBOB', 'HiBob'), ('DEEL', 'Deel'), ('ZOHO_PEOPLE', 'Zoho People'), ('ADP', 'ADP'), ('GUSTO', 'Gusto'), ('PAYCHEX', 'Paychex'), ('UKG', 'UKG'), ('PAYLOCITY', 'Paylocity'), ('QUICKBOOKS', 'QuickBooks'), ('XERO', 'Xero'), ('SAGE', 'Sage'), ('ZOHO_BOOKS', 'Zoho Books'), ('FRESHBOOKS', 'FreshBooks'), ('NETSUITE', 'NetSuite'), ('MICROSOFT_ENTRA', 'Microsoft Entra ID'), ('OKTA', 'Okta'), ('GOOGLE_WORKSPACE', 'Google Workspace'), ('ONELOGIN', 'OneLogin'), ('JUMPCLOUD', 'JumpCloud'), ('PING_IDENTITY', 'Ping Identity'), ('SAP', 'SAP'), ('ORACLE', 'Oracle'), ('MICROSOFT_DYNAMICS', 'Microsoft Dynamics 365'), ('ODOO', 'Odoo'), ('ACUMATICA', 'Acumatica')], max_length=50)),
                ('status', models.CharField(choices=[('DISCONNECTED', 'Disconnected'), ('CONNECTED', 'Connected'), ('ERROR', 'Error'), ('EXPIRED', 'Expired')], default='DISCONNECTED', max_length=30)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, default='')),
                ('external_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='tenants.company')),
            ],
            options={
                'ordering': ['category', 'provider'],
                'constraints': [models.UniqueConstraint(fields=('company', 'provider'), name='unique_company_provider_integration')],
            },
        ),
    ]
