# Generated by Django 5.2.15 on 2026-08-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integration_bamboohr_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('BAMBOOHR', 'BambooHR'), ('RIPPLING', 'Rippling'), ('WORKDAY', 'Workday'), ('HIBOB', 'HiBob'), ('DEEL', 'Deel'), ('ZOHO_PEOPLE', 'Zoho People'), ('ADP', 'ADP'), ('GUSTO', 'Gusto'), ('PAYCHEX', 'Paychex'), ('UKG', 'UKG'), ('PAYLOCITY', 'Paylocity'), ('QUICKBOOKS', 'QuickBooks'), ('XERO', 'Xero'), ('SAGE', 'Sage'), ('ZOHO_BOOKS', 'Zoho Books'), ('FRESHBOOKS', 'FreshBooks'), ('NETSUITE', 'NetSuite'), ('MICROSOFT_ENTRA', 'Microsoft Entra ID'), ('OKTA', 'Okta'), ('GOOGLE_WORKSPACE', 'Google Workspace'), ('ONELOGIN', 'OneLogin'), ('JUMPCLOUD', 'JumpCloud'), ('PING_IDENTITY', 'Ping Identity'), ('SAP', 'SAP'), ('ORACLE', 'Oracle'), ('MICROSOFT_DYNAMICS', 'Microsoft Dynamics 365'), ('ODOO', 'Odoo'), ('ACUMATICA', 'Acumatica'), ('MOCK', 'Mock Provider')], max_length=50),
        ),
    ]
