# Generated by Django 5.2.15 on 2026-08-17 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_externalemployee'),
        ('tenants', '0042_companyrole_can_manage_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='company',
        ),
        migrations.CreateModel(
            name='CompanyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('BAMBOOHR', 'BambooHR'), ('RIPPLING', 'Rippling'), ('WORKDAY', 'Workday'), ('ADP', 'ADP'), ('QUICKBOOKS', 'QuickBooks')], max_length=30)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=30, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='tenants.company')),
            ],
        ),
        migrations.DeleteModel(
            name='ExternalEmployee',
        ),
        migrations.DeleteModel(
            name='Integration',
        ),
        migrations.AddConstraint(
            model_name='companyintegration',
            constraint=models.UniqueConstraint(fields=('company', 'provider'), name='unique_company_integration_provider'),
        ),
    ]
