# Generated by Django 5.2.15 on 2026-08-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_integrationcredential'),
        ('tenants', '0043_companyrole_can_manage_integrations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_employee_id', models.CharField(max_length=255)),
                ('external_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='integrations.companyintegration')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_mappings', to='tenants.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('integration', 'external_employee_id'), name='unique_integration_external_employee'), models.UniqueConstraint(fields=('integration', 'user_profile'), name='unique_integration_user_profile')],
            },
        ),
    ]
