# Generated by Django 5.2.15 on 2026-08-17 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_integrationsynclog'),
        ('tenants', '0043_companyrole_can_manage_integrations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_oauth_states', to='tenants.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
