# Generated by Django 5.2.15 on 2026-08-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_quickbooksoauthstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zepex_category', models.CharField(max_length=50)),
                ('quickbooks_account_id', models.CharField(max_length=100)),
                ('quickbooks_account_name', models.CharField(max_length=255)),
                ('quickbooks_account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('quickbooks_account_sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_category_mappings', to='integrations.companyintegration')),
            ],
            options={
                'ordering': ['zepex_category'],
                'constraints': [models.UniqueConstraint(fields=('integration', 'zepex_category'), name='unique_quickbooks_category_mapping')],
            },
        ),
    ]
