# Generated by Django 5.2.15 on 2026-08-17 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0030_notification'),
        ('integrations', '0010_quickbookscategorymapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('exported_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_exports', to='integrations.companyintegration')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quickbooks_exports', to='expenses.expensereport')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('integration', 'report'), name='unique_quickbooks_report_export')],
            },
        ),
    ]
