# Generated by Django 5.2.15 on 2026-08-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_quickbooksexportrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='quickbooks_payment_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='quickbooks_payment_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='quickbooks_payment_account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
