# Generated by Django 5.2.15 on 2026-08-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_companyintegration_quickbooks_payment_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('DEPARTMENT', 'Department')], max_length=30)),
                ('external_resource_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255, null=True)),
                ('change_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ACTIVATED', 'Activated'), ('DEACTIVATED', 'Deactivated'), ('MANAGER_CHANGED', 'Manager Changed'), ('DEPARTMENT_CHANGED', 'Department Changed')], max_length=50)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='integrations.companyintegration')),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='integrations.integrationsynclog')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['integration', 'created_at'], name='integration_integra_a78d13_idx'), models.Index(fields=['integration', 'resource_type'], name='integration_integra_322351_idx'), models.Index(fields=['integration', 'change_type'], name='integration_integra_552610_idx')],
            },
        ),
    ]
