# Generated by Django 5.2.15 on 2026-09-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_ensure_quickbooks_payment_account_columns'),
        ('integrations', '0013_integrationchangelog'),
    ]

    operations = [
    ]
