# Generated by Django 5.2.15 on 2026-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_merge_20260901_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='quickbooks_auto_export',
            field=models.BooleanField(default=False, help_text='Automatically export PAID expense reports to QuickBooks.'),
        ),
    ]
