# Generated by Django 5.2.15 on 2026-09-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_companyintegration_quickbooks_auto_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbooksexportrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
