# Generated by Django 5.2.15 on 2026-09-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_alter_quickbooksexportrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksexportrecord',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksexportrecord',
            name='reconciliation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quickbooksexportrecord',
            name='reconciliation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksexportrecord',
            name='reconciliation_status',
            field=models.CharField(choices=[('NOT_CHECKED', 'Not Checked'), ('VERIFIED', 'Verified'), ('MISMATCH', 'Mismatch'), ('MISSING', 'Missing'), ('ERROR', 'Error')], default='NOT_CHECKED', max_length=20),
        ),
    ]
