# Generated by Django 5.2.15 on 2026-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_quickbooksexportrecord_reconciled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='bamboohr_webhook_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='bamboohr_webhook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='bamboohr_webhook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
