# Generated by Django 5.2.15 on 2026-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_companyintegration_bamboohr_webhook_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsynclog',
            name='trigger',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('WEBHOOK', 'Webhook')], default='MANUAL', max_length=20),
        ),
    ]
