# Generated by Django 5.2.15 on 2026-09-05 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0031_expenselineitem_company_amount_and_more'),
        ('integrations', '0019_alter_integrationsynclog_trigger'),
        ('tenants', '0045_userprofile_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BambooHRPayrollBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payroll_period_start', models.DateField()),
                ('payroll_period_end', models.DateField()),
                ('pay_date', models.DateField()),
                ('earning_code', models.CharField(default='EXPENSE_REIMBURSEMENT', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('EXPORTED', 'Exported'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('payroll_run_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bamboohr_payroll_batches', to='tenants.userprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bamboohr_payroll_batches', to='tenants.userprofile')),
                ('integration', models.ForeignKey(limit_choices_to={'provider': 'BAMBOOHR'}, on_delete=django.db.models.deletion.PROTECT, related_name='bamboohr_payroll_batches', to='integrations.companyintegration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BambooHRPayrollBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_employee_id', models.CharField(max_length=255)),
                ('employee_number', models.CharField(blank=True, default='', max_length=255)),
                ('external_email', models.EmailField(blank=True, default='', max_length=254)),
                ('employee_name', models.CharField(max_length=255)),
                ('bamboohr_employee_status', models.CharField(blank=True, default='', max_length=50)),
                ('include_in_payroll', models.BooleanField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('earning_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXPORTED', 'Exported'), ('CONFIRMED', 'Confirmed'), ('REMOVED', 'Removed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integrations.bamboohrpayrollbatch')),
                ('employee_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bamboohr_payroll_items', to='integrations.integrationemployeemapping')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bamboohr_payroll_items', to='expenses.expensereport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bamboohrpayrollbatch',
            index=models.Index(fields=['integration', 'status', 'pay_date'], name='bamboo_payroll_batch_idx'),
        ),
        migrations.AddConstraint(
            model_name='bamboohrpayrollbatch',
            constraint=models.CheckConstraint(condition=models.Q(('payroll_period_start__lte', models.F('payroll_period_end'))), name='bamboo_payroll_valid_period'),
        ),
        migrations.AddIndex(
            model_name='bamboohrpayrollbatchitem',
            index=models.Index(fields=['batch', 'status'], name='bamboo_payroll_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='bamboohrpayrollbatchitem',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'EXPORTED', 'CONFIRMED'])), fields=('report',), name='unique_active_bamboo_payroll_report'),
        ),
        migrations.AddConstraint(
            model_name='bamboohrpayrollbatchitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bamboo_payroll_positive_amount'),
        ),
    ]
