# Generated by Django 5.2.15 on 2026-08-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0011_alter_auditlog_action_receipt_deleted'),
        ('tenants', '0043_companyrole_can_manage_integrations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('RECEIPT_UPLOADED', 'Receipt Uploaded'), ('EMAIL_RECEIPT_RECEIVED', 'Email Receipt Received'), ('AI_PROCESSING_STARTED', 'AI Processing Started'), ('AI_PROCESSED', 'AI Processed'), ('LINE_ITEM_DELETED', 'Line Item Deleted'), ('RECEIPT_DELETED', 'Receipt Deleted'), ('REPORT_SUBMITTED', 'Report Submitted'), ('STEP_APPROVED', 'Step Approved'), ('STEP_REJECTED', 'Step Rejected'), ('MARKED_PAID', 'Marked Paid'), ('WORKFLOW_CONFIGURED', 'Workflow Configured'), ('WORKFLOW_STEP_CREATED', 'Workflow Step Created'), ('EMAIL_FETCH_TRIGGERED', 'Email Fetch Triggered'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DELETED', 'User Deleted'), ('DEPARTMENT_CREATED', 'Department Created'), ('DEPARTMENT_UPDATED', 'Department Updated'), ('DEPARTMENT_DEACTIVATED', 'Department Deactivated'), ('DEPARTMENT_ACTIVATED', 'Department Activated'), ('DEPARTMENT_DELETED', 'Department Deleted'), ('COMPANY_DEACTIVATED', 'Company Deactivated'), ('COMPANY_ACTIVATED', 'Company Activated'), ('POLICY_UPDATED', 'Policy Updated'), ('POLICY_RULE_UPDATED', 'Policy Rule Updated'), ('POLICY_RULE_DEACTIVATED', 'Policy Rule Deactivated'), ('POLICY_RULE_ACTIVATED', 'Policy Rule Activated'), ('POLICY_RULE_DELETED', 'Policy Rule Deleted'), ('DATABASE_CONNECTED', 'Database Connected'), ('DATABASE_CONNECTION_FAILED', 'Database Connection Failed'), ('SYNC_STARTED', 'Sync Started'), ('SYNC_COMPLETED', 'Sync Completed'), ('SYNC_FAILED', 'Sync Failed'), ('BAMBOOHR_CONNECTED', 'BambooHR Connected'), ('BAMBOOHR_CONNECTION_FAILED', 'BambooHR Connection Failed'), ('BAMBOOHR_SYNC_STARTED', 'BambooHR Sync Started'), ('BAMBOOHR_SYNC_COMPLETED', 'BambooHR Sync Completed'), ('BAMBOOHR_SYNC_FAILED', 'BambooHR Sync Failed'), ('BAMBOOHR_DISCONNECTED', 'BambooHR Disconnected'), ('QUICKBOOKS_CONNECTED', 'QuickBooks Connected'), ('QUICKBOOKS_CONNECTION_FAILED', 'QuickBooks Connection Failed'), ('QUICKBOOKS_DISCONNECTED', 'QuickBooks Disconnected'), ('QUICKBOOKS_MAPPING_CREATED', 'QuickBooks Mapping Created'), ('QUICKBOOKS_MAPPING_UPDATED', 'QuickBooks Mapping Updated'), ('QUICKBOOKS_MAPPING_DELETED', 'QuickBooks Mapping Deleted'), ('QUICKBOOKS_EXPORT_QUEUED', 'QuickBooks Export Queued'), ('QUICKBOOKS_EXPORT_STARTED', 'QuickBooks Export Started'), ('QUICKBOOKS_EXPORT_SUCCESS', 'QuickBooks Export Successful'), ('QUICKBOOKS_EXPORT_FAILED', 'QuickBooks Export Failed'), ('QUICKBOOKS_EXPORT_RETRIED', 'QuickBooks Export Retried')], max_length=60),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'action'], name='audit_logs__company_0ba269_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'created_at'], name='audit_logs__company_83ad73_idx'),
        ),
    ]
