# Generated by Django 5.2.15 on 2026-07-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_incomingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingemail',
            name='recipient_email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
