# Generated by Django 5.2.15 on 2026-08-04 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_incomingemail_recipient_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensereceipt',
            options={},
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='linked_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_receipts', to='expenses.expensereceipt'),
        ),
    ]
