# Generated by Django 5.2.15 on 2026-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_alter_expensereceipt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselineitem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='fingerprint_hash',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='receipt_fingerprint',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
