# Generated by Django 5.2.15 on 2026-08-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_expenselineitem_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereceipt',
            name='ai_confidence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
