# Generated by Django 5.2.15 on 2026-08-04 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_expensereceipt_ai_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='expense_attachments/%Y/%m/%d/')),
                ('attachment_type', models.CharField(default='receipt', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='expenses.expenselineitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='expenses.expensereceipt')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
