# Generated by Django 5.2.15 on 2026-08-04 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0023_expenseattachment'),
        ('tenants', '0034_seed_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('RECEIPT_UPLOADED', 'Receipt Uploaded'), ('AI_STARTED', 'AI Started'), ('AI_COMPLETED', 'AI Completed'), ('LINE_ITEMS_CREATED', 'Line Items Created'), ('DUPLICATE_CHECK', 'Duplicate Check'), ('RECEIPT_LINKED', 'Receipt Linked'), ('POLICY_VALIDATED', 'Policy Validated'), ('APPROVAL_STARTED', 'Approval Started'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.userprofile')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='expenses.expensereceipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
