# Generated by Django 5.2.15 on 2026-08-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_expenseaudittrail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensereceipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='linked_reference_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='reference_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
