# Generated by Django 5.2.15 on 2026-08-12 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_alter_expensereceipt_options_and_more'),
        ('tenants', '0037_delete_companyintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselineitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_expense_line_items', to='tenants.userprofile'),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('REPORT_SUBMITTED', 'Report Submitted'), ('STEP_APPROVED', 'Step Approved'), ('STEP_REJECTED', 'Step Rejected'), ('RECEIPT_APPROVED', 'Receipt Approved'), ('RECEIPT_REJECTED', 'Receipt Rejected'), ('LINE_ITEM_UPDATED', 'Line Item Updated'), ('LINE_ITEM_RESTORED', 'Line Item Restored'), ('PAID', 'Paid')], max_length=40),
        ),
    ]
