# Generated by Django 5.2.15 on 2026-08-12 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0026_expenselineitem_deleted_at_and_more'),
        ('tenants', '0037_delete_companyintegration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenselineitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='expenselineitem',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='expenselineitem',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='removal_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_expense_line_items', to='tenants.userprofile'),
        ),
    ]
