# Generated by Django 5.2.15 on 2026-08-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0027_remove_expenselineitem_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('REPORT_SUBMITTED', 'Report Submitted'), ('STEP_APPROVED', 'Step Approved'), ('STEP_REJECTED', 'Step Rejected'), ('RECEIPT_APPROVED', 'Receipt Approved'), ('RECEIPT_REJECTED', 'Receipt Rejected'), ('LINE_ITEM_UPDATED', 'Line Item Updated'), ('LINE_ITEM_REMOVED', 'Line Item Removed'), ('LINE_ITEM_RESTORED', 'Line Item Restored'), ('PAID', 'Paid')], max_length=40),
        ),
    ]
