# Generated by Django 5.2.15 on 2026-08-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0028_alter_approvalhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalhistory',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_history', to='expenses.expenselineitem'),
        ),
    ]
