# Generated by Django 5.2.15 on 2026-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0030_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselineitem',
            name='company_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='company_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='original_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
