# Generated by Django 5.2.15 on 2026-08-05 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0034_seed_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(db_index=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_admins', to='tenants.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_admins', to='tenants.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_admin', to='tenants.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='platform_access.platformadmin')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_admins', to='platform_access.platformpermission')),
            ],
            options={
                'unique_together': {('platform_admin', 'permission')},
            },
        ),
    ]
