# Generated by Django 5.2.15 on 2026-08-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_access", "0002_seed_platform_permissions"),
        ("tenants", "0038_userprofile_platform_admin_nullable_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformadmin",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_admins",
                to="tenants.company",
            ),
        ),
    ]
